### ISSUE TITLE
CAUGHT TypeError: this._connection.close is not a function

### ISSUE THREAD

**Issue by swaheed2** [sy1vain/node-pjlink#9]
```
CAUGHT TypeError: this._connection.close is not a function
    at PJLink._resetConnection (/node_modules/pjlink/lib/pjlink.js:232:20)
    at PJLink._onClose (/node_modules/pjlink/lib/pjlink.js:219:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)


````

**Comment by sy1vain** [comment]
This has already been fixed quite a while ago. I will check if nom has the latest version, if not until then you can use the gothic version.

**Comment by sy1vain** [comment]
Npm was already updated. Please check if you have the latest version.
